export const MY_ORDERS_REQUEST =  'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS =  'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL =  'MY_ORDERS_FAIL'

export const CLEAR_ERRORS  = 'CLEAR_ERRORS'
